### ISSUE TITLE
PHP Warnings filling up log

### ISSUE THREAD

**Issue by jpSimkins** [mvied/wordpress-https#50]
I came in today and noticed my log is full of these PHP Warnings.

```
PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /wp-content/plugins/wordpress-https/lib/WordPressHTTPS.php on line 352
PHP Warning:  Illegal offset type in /wp-content/plugins/wordpress-https/lib/WordPressHTTPS.php on line 359
```

I'll be working on a fix but wanted to make note of it here.

**Comment by fulopattila122** [comment]
It's still happening to me, also reported here:
https://wordpress.org/support/topic/bug-php-warning-illegal-offset-type/

The problem is that the `isUrlLocal($url)` method in WordPressHTTPS.php sometims receives an `Mvied_Url` object. ~I'll shortly submit a PR that fixes it~. Apparently it's been fixed along with #59
